version: "3.7"
services:
  db:
    build: ./mysql-microservice

    volumes:
      - ./pool-test/testing_mysql/mysql-microservice/data:/var/lib/mysql 
    
    ports:
      - "6603:3306"

  web:
    build: ./teamway-be

    volumes:
      - /teamway-be/node_modules
      - ./teamway-be:/teamway-be

    depends_on:
      - db

    ports:
      - "4000:4000"